---
output:
  github_document:
    toc: true
    toc_depth: 3
    includes:
      before_body: README-header.md
always_allow_html: yes
editor_options:
  markdown:
    wrap: sentence
---

```{r include = FALSE}
oldhook <- knitr::knit_hooks$get("source")
knitr::knit_hooks$set(source = function(x, options) {
  oldhook(sub("await import('./index.js')", "require('rversions')", x, fixed = TRUE), options)
})
knitr::opts_chunk$set(engine.opts = list(node = "--input-type=module"))
```

## Install

```
$ npm install rversions
```

## CLI

Install globally to get the `rver` command:

    $ npm install -g rversions

### rver available

List available R versions. Prints one version string per line by default; use
`--json` for full objects.

```sh
$ rver available | tail -3
4.5.3   https://cran.rstudio.com/src/base/R-4/R-4.5.3.tar.gz
4.6.0   https://cran.rstudio.com/src/base/R-4/R-4.6.0.tar.gz
4.7.0   https://cran.rstudio.com/src/base-prerelease/R-devel.tar.gz

$ rver available --os win --arch x86_64 | tail -3
4.5.3   https://cran.rstudio.com/bin/windows/base/old/4.5.3/R-4.5.3-win.exe
4.6.0   https://cran.rstudio.com/bin/windows/base/R-4.6.0-win.exe
4.7.0   https://cran.rstudio.com/bin/windows/base/R-devel-win.exe

$ rver available --os linux-ubuntu-22.04 --json
[...]
```

### rver resolve

Resolve a version specifier to a specific version and download URL.
Prints `version<TAB>url` by default; use `--json` for the full object.

```sh
$ rver resolve release
4.6.0   https://cran.rstudio.com/src/base/R-4/R-4.6.0.tar.gz

$ rver resolve release --os win --arch x86_64
4.6.0   https://cran.rstudio.com/bin/windows/base/R-4.6.0-win.exe

$ rver resolve 4.4 --os mac --arch arm64 --json
{
  "version": "4.4.3",
  ...
}
```

Supported version specifiers: `release`, `devel`, `next`, `oldrel`,
`oldrel/2`, a minor version like `4.4`, or a full version like `4.4.3`.

### rver rtools-versions

List Rtools versions with the range of R versions they support and their
download URL. Use `--arch aarch64` for the Windows ARM64 builds.

```sh
$ rver rtools-versions | tail -3
43      4.3.0..4.3.100  https://github.com/r-hub/rtools43/releases/download/latest/rtools43.exe
44      4.4.0..4.4.100  https://github.com/r-hub/rtools44/releases/download/latest/rtools44.exe
45      4.5.0..100.0.0  https://github.com/r-hub/rtools45/releases/download/latest/rtools45.exe
```

### rver linux-distros

List supported Linux distributions. Prints one distro ID per line; use the ID
with the `linux-` prefix as the `--os` value for the other commands.

```sh
$ rver linux-distros | head -5
ubuntu-1604
ubuntu-1804
ubuntu-2004
ubuntu-2204
ubuntu-2404

$ rver linux-distros --json
[...]
```

## Usage

### Resolution

#### R-devel

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("devel"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("devel", "win"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("devel", "macos"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("devel", "linux-ubuntu-26.04"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("devel", "linux-ubuntu-26.04", "arm64"));
```

#### R-next

This can be an alpha, beta, RC or pre-release if a release process is
currently happenning. Otherwise it is the current patched version.

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("next"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("next", "win"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("next", "macos"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("next", "linux-ubuntu-26.04"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("next", "linux-ubuntu-26.04", "arm64"));
```

#### R-release

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("release"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("release", "win"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("release", "macos"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("release", "linux-ubuntu-26.04"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("release", "linux-ubuntu-26.04", "arm64"));
```

#### R-oldrel

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("oldrel/1"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("oldrel/1", "win"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("oldrel/1", "macos"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("oldrel/1", "linux-ubuntu-26.04"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("oldrel/1", "linux-ubuntu-26.04", "arm64"));
```

#### Specific R version

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("4.2.2"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("4.2.2", "win"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("4.2.2", "macos"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("4.2.2", "linux-ubuntu-26.04"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("4.2.2", "linux-ubuntu-26.04", "arm64"));
```

#### Minor R version

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("4.1"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("4.1", "win"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("4.1", "macos"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("4.1", "linux-ubuntu-26.04"));
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.resolve("4.1", "linux-ubuntu-26.04", "arm64"));
```

### Available builds for a platform

```{node}
const builds = await import('./index.js');
console.log(await builds.available("linux-ubuntu-26.04"));
```

### List all R releases

```{node}
const rversions = await import('./index.js');
console.log(await rversions.r_versions());
```

### List all Rtools versions

```{node}
const rversions = await import('./index.js');
console.log(await rversions.rtools_versions());
```

```{node}
const rversions = await import('./index.js');
console.log(await rversions.rtools_versions("aarch64"));
```

### List supported Linux distros

```{node}
const rversions = await import('./index.js');
console.log(await rversions.linux_distros());
```

## Caching

All queries are cached for five minutes by default. If you don't want to
use the cached value, then set the (first) cache argument to `false`.

You can adjust the default caching time limit by setting the
`R_VERSIONS_CACHE_LIMIT` environment variable in milliseconds. E.g. the
default five minutes is 5 * 60 * 1000 = 300000.

## License

ISC @ R Consortium

This repo is part of the R-hub project, supported by
the R Consortium.
